# -*- coding: utf-8 -*-
"""
Datos de las recetas. Fuente única de verdad: tools/build.py genera todas las
páginas HTML a partir de esta lista. Para cambiar una receta, edítala aquí y
vuelve a ejecutar:  python3 tools/build.py

Campos:
  slug        nombre de archivo (receta-<slug>.html) e imagen (assets/img/<slug>.webp)
  total       minutos aproximados de principio a fin
  time_breakdown  en qué se van esos minutos
  ingredients cantidades para "servings" raciones: [200] = cantidad que se
              recalcula al cambiar las raciones, [3-4] = rango,
              {singular|plural} = palabra que concuerda con la cantidad anterior
  steps       lista de (texto, minutos_de_temporizador | None)
  need        ingredientes principales para el buscador "¿Qué tengo en la nevera?"
              (sal, pimienta, aceite y azúcar se dan por hechos)
"""

RECIPES = [
    {
        "slug": "carbonara",
        "title": "Espaguetis a la carbonara",
        "category": "Pasta",
        "summary": "La receta romana: guanciale, yema de huevo, pecorino y pimienta negra. Sin nata: la crema sale del huevo y del agua de cocción.",
        "servings": 2,
        "total": 20,
        "time_breakdown": ['Calentar el agua: 8–10 min (mientras preparas el guanciale, el queso y el huevo)', 'Cocer la pasta: 9–11 min (el guanciale se dora a la vez)', 'Mezclar y servir: 2 min'],
        "difficulty": "Media",
        "ingredients": [
            "[200] g de espaguetis",
            "[100] g de guanciale (o panceta curada si no lo encuentras)",
            "[2] {yema|yemas} de huevo y [1] {huevo entero|huevos enteros}",
            "[40] g de queso pecorino romano rallado, y un poco más para servir",
            "Pimienta negra recién molida",
            "Sal gruesa para el agua de cocción",
        ],
        "tools": [
            "Olla grande",
            "Sartén amplia",
            "Bol",
            "Rallador",
            "Tenedor o varillas",
            "Pinzas de cocina",
            "Colador",
            "Cuchillo y tabla de cortar",
        ],
        "steps": [
            ("Pon a calentar agua abundante en la olla grande. Cuando hierva, échale un buen puñado de sal gruesa.", None),
            ("Mientras se calienta el agua, corta el guanciale en tiras de medio centímetro de grosor y ralla el pecorino.", None),
            ("En el bol, bate las yemas y el huevo entero con el pecorino rallado y abundante pimienta negra hasta obtener una pasta espesa. Resérvala.", None),
            ("Echa los espaguetis en el agua hirviendo y cuécelos el tiempo que indique el paquete para que queden al dente (en la mayoría de marcas, entre 9 y 11 minutos).", 10),
            ("Mientras la pasta se cuece, pon el guanciale en la sartén sin aceite, a fuego medio. Deja que suelte su grasa y se dore hasta quedar crujiente por fuera, unos 5–7 minutos. Apaga el fuego.", 6),
            ("Antes de escurrir la pasta, reserva un vaso del agua de cocción. Escurre los espaguetis y pásalos a la sartén con el guanciale, con el fuego apagado. Mézclalo todo con las pinzas.", None),
            ("Añade la mezcla de huevo y queso y remueve rápido, incorporando el agua de cocción poco a poco (a cucharadas) hasta que se forme una crema brillante que envuelva la pasta. Hazlo fuera del fuego: si la sartén está demasiado caliente, el huevo cuaja y queda en grumos.", None),
            ("Sirve enseguida con un poco más de pecorino y pimienta molida por encima.", None),
        ],
        "tips": [
            "La receta romana tradicional no lleva nata, ni cebolla, ni ajo.",
            "Si sustituyes el pecorino por parmesano, el sabor será más suave y menos salado.",
        ],
        "image_query": "spaghetti carbonara",
        "need": ["pasta", "huevos", "panceta o guanciale", "queso"],
    },
    {
        "slug": "gambas-al-ajillo",
        "title": "Gambas al ajillo",
        "category": "Pescado y marisco",
        "summary": "Un clásico de la cocina española: gambas cocinadas en aceite de oliva con ajo laminado y guindilla. Se sirven hirviendo, con pan para mojar.",
        "servings": 2,
        "total": 15,
        "time_breakdown": ['Preparar ingredientes: 8 min', 'Cocinar: 4–5 min'],
        "difficulty": "Fácil",
        "ingredients": [
            "[300] g de gambas peladas (crudas)",
            "[4] {diente|dientes} de ajo",
            "[1] {guindilla|guindillas} (cayena) {seca|secas}",
            "[80] ml de aceite de oliva virgen extra",
            "Un puñado de perejil fresco",
            "Sal",
            "Pan, para acompañar",
        ],
        "tools": [
            "Cazuela de barro pequeña o sartén pequeña",
            "Cuchillo y tabla de cortar",
            "Papel de cocina",
            "Cuchara de madera o espátula",
        ],
        "steps": [
            ("Si las gambas están congeladas, descongélalas antes (en la nevera, la noche anterior). Sécalas bien con papel de cocina y sálalas ligeramente.", None),
            ("Pela los ajos y córtalos en láminas finas. Pica el perejil. Parte la guindilla en dos o tres trozos.", None),
            ("Pon el aceite en la cazuela a fuego medio-bajo y añade el ajo y la guindilla. Deja que el ajo se cocine despacio hasta que empiece a tomar un color dorado muy claro, 1–2 minutos. No dejes que se tueste de más o amargará.", 2),
            ("Sube el fuego a medio-alto y añade las gambas. Cocínalas 2–3 minutos, dándoles la vuelta a mitad, hasta que cambien de color gris a rosado y estén opacas.", 3),
            ("Apaga el fuego, espolvorea el perejil picado y sirve enseguida en la misma cazuela, con pan para mojar el aceite.", None),
        ],
        "tips": [
            "Con gambas pequeñas, reduce el tiempo de cocción: si se pasan, quedan duras.",
            "La cazuela de barro mantiene el calor y el aceite sigue burbujeando al llegar a la mesa.",
        ],
        "image_query": "gambas al ajillo",
        "need": ["gambas", "ajo"],
    },
    {
        "slug": "ensalada-caprese",
        "title": "Ensalada caprese",
        "category": "Sin cocción",
        "summary": "Tomate, mozzarella fresca y albahaca: los colores de la bandera italiana en un plato que no necesita fuego. Depende por completo de la calidad del tomate.",
        "servings": 2,
        "total": 10,
        "time_breakdown": ['Cortar y montar: 10 min', 'Sin cocción'],
        "difficulty": "Fácil",
        "ingredients": [
            "[2] {tomate maduro grande|tomates maduros grandes}",
            "[1] {bola|bolas} de mozzarella fresca (unos [125] g en total)",
            "Un puñado de hojas de albahaca fresca",
            "Aceite de oliva virgen extra",
            "Sal en escamas",
            "Pimienta negra",
        ],
        "tools": [
            "Cuchillo afilado o de sierra",
            "Tabla de cortar",
            "Fuente o plato llano",
            "Papel de cocina",
        ],
        "steps": [
            ("Lava los tomates, sécalos y córtalos en rodajas de aproximadamente 1 cm de grosor.", None),
            ("Escurre la mozzarella del suero, sécala suavemente con papel de cocina y córtala en rodajas de grosor parecido al del tomate.", None),
            ("Coloca en la fuente las rodajas de tomate y de mozzarella alternándolas, ligeramente superpuestas.", None),
            ("Lava y seca las hojas de albahaca y repártelas entre las rodajas.", None),
            ("Justo antes de servir, aliña con un buen chorro de aceite de oliva, sal en escamas y pimienta negra.", None),
        ],
        "tips": [
            "La versión clásica se aliña solo con aceite, sal y pimienta; el vinagre balsámico es opcional.",
            "Saca los tomates de la nevera con antelación: a temperatura ambiente tienen más sabor.",
        ],
        "image_query": "caprese salad",
        "need": ["tomate", "mozzarella", "albahaca"],
    },
    {
        "slug": "salmon-con-esparragos",
        "title": "Salmón a la plancha con espárragos trigueros",
        "category": "Pescado y marisco",
        "summary": "Lomos de salmón con la piel crujiente y espárragos trigueros salteados en la misma sartén. Se termina con unas gotas de limón.",
        "servings": 2,
        "total": 20,
        "time_breakdown": ['Preparar: 5 min', 'Saltear los espárragos: 5–6 min', 'Cocinar el salmón: 6–7 min'],
        "difficulty": "Fácil",
        "ingredients": [
            "[2] {lomo|lomos} de salmón con piel (unos 150 g cada uno)",
            "[1] {manojo|manojos} de espárragos trigueros (unos [250] g en total)",
            "[1] {limón|limones}",
            "[2] {cucharada|cucharadas} de aceite de oliva",
            "Sal",
            "Pimienta negra",
        ],
        "tools": [
            "Sartén antiadherente grande o plancha",
            "Espátula o pinzas",
            "Cuchillo y tabla de cortar",
            "Papel de cocina",
            "Plato para reservar",
        ],
        "steps": [
            ("Seca bien los lomos de salmón con papel de cocina (así la piel se dora y no se pega) y salpimiéntalos por ambos lados.", None),
            ("Lava los espárragos. Dobla cada uno por la base: se parte solo por donde deja de ser leñoso. Desecha la parte dura.", None),
            ("Calienta la mitad del aceite en la sartén a fuego medio-alto. Saltea los espárragos 5–6 minutos, moviéndolos de vez en cuando, hasta que estén tiernos y algo dorados. Sálalos y resérvalos en un plato.", 5),
            ("En la misma sartén, añade el resto del aceite y coloca el salmón con la piel hacia abajo. Cocínalo unos 4 minutos sin moverlo, hasta que la piel esté crujiente y veas que el color opaco sube por el lateral.", 4),
            ("Dale la vuelta y cocínalo 2–3 minutos más. El tiempo exacto depende del grosor: el centro debe quedar opaco y la carne debe separarse en láminas al presionarla.", 3),
            ("Sirve el salmón con los espárragos y un gajo de limón para exprimir por encima.", None),
        ],
        "tips": [
            "Con lomos muy gruesos (más de 3 cm), añade 1–2 minutos más por el segundo lado.",
        ],
        "image_query": "grilled salmon asparagus",
        "need": ["salmón", "espárragos"],
    },
    {
        "slug": "quesadillas",
        "title": "Quesadillas de queso y champiñones",
        "category": "Verduras",
        "summary": "Tortillas de trigo dobladas y tostadas en sartén, rellenas de queso fundido y champiñones salteados con cebolla.",
        "servings": 2,
        "total": 20,
        "time_breakdown": ['Preparar: 5 min', 'Saltear el relleno: 6 min', 'Tostar las quesadillas: 8 min'],
        "difficulty": "Fácil",
        "ingredients": [
            "[2] {tortilla|tortillas} de trigo {grande|grandes}",
            "[150] g de queso que funda bien (Oaxaca, mozzarella o cheddar), rallado",
            "[150] g de champiñones",
            "[0.5] {cebolla|cebollas}",
            "[1] {cucharada|cucharadas} de aceite de oliva",
            "Sal",
        ],
        "tools": [
            "Sartén grande",
            "Espátula ancha",
            "Cuchillo y tabla de cortar",
            "Rallador (si el queso no viene rallado)",
            "Plato",
        ],
        "steps": [
            ("Limpia los champiñones con papel de cocina húmedo y córtalos en láminas. Pica la cebolla fina.", None),
            ("Calienta el aceite en la sartén a fuego medio y saltea la cebolla y los champiñones con una pizca de sal durante 5–6 minutos, hasta que los champiñones suelten su agua y esta se evapore. Pásalos a un plato.", 6),
            ("Limpia la sartén con papel de cocina y vuelve a ponerla a fuego medio, sin aceite.", None),
            ("Coloca una tortilla en la sartén y, sobre una de sus mitades, reparte la parte de champiñones y de queso que le corresponde (el relleno se divide a partes iguales entre las tortillas). Dobla la tortilla por la mitad y presiónala con la espátula.", None),
            ("Tuéstala unos 2 minutos por cada lado, hasta que esté dorada y el queso se haya fundido. Repite con el resto de tortillas.", 2),
            ("Deja reposar un minuto para que el queso no se salga al cortar y córtalas en triángulos.", None),
        ],
        "tips": [
            "Si tu sartén es grande, puedes tostar dos quesadillas a la vez y ahorrar unos minutos.",
        ],
        "image_query": "quesadilla cheese mushroom",
        "need": ["tortillas de trigo", "queso", "champiñones", "cebolla"],
    },
    {
        "slug": "cuscus-con-verduras",
        "title": "Cuscús con verduras salteadas",
        "category": "Verduras",
        "summary": "La sémola de cuscús precocida solo necesita líquido caliente y unos minutos de reposo; mientras tanto, se saltean las verduras.",
        "servings": 2,
        "total": 20,
        "time_breakdown": ['Cortar las verduras: 7 min', 'Saltear: 10 min (el cuscús reposa a la vez)'],
        "difficulty": "Fácil",
        "ingredients": [
            "[150] g de cuscús (sémola precocida)",
            "[150] ml de agua o caldo de verduras",
            "[1] {calabacín|calabacines}",
            "[1] {pimiento rojo|pimientos rojos}",
            "[0.5] {cebolla|cebollas}",
            "[2] {cucharada|cucharadas} de aceite de oliva",
            "[1] {cucharadita|cucharaditas} de comino molido",
            "Sal",
            "Pimienta negra",
        ],
        "tools": [
            "Cazo",
            "Sartén",
            "Bol resistente al calor con tapa (o un plato para taparlo)",
            "Tenedor",
            "Cuchillo y tabla de cortar",
        ],
        "steps": [
            ("Lava el calabacín y el pimiento. Córtalos en dados pequeños, junto con la cebolla, para que se hagan rápido.", None),
            ("Calienta la mitad del aceite en la sartén a fuego medio y sofríe la cebolla 3 minutos.", 3),
            ("Añade el pimiento y el calabacín, sala y cocina 6–7 minutos removiendo de vez en cuando, hasta que estén tiernos. Añade el comino y la pimienta en el último minuto.", 6),
            ("Mientras se hacen las verduras, calienta el agua o el caldo en el cazo con una pizca de sal y el resto del aceite hasta que hierva.", None),
            ("Pon el cuscús en el bol, vierte el líquido hirviendo por encima, tápalo y déjalo reposar 5 minutos (o lo que indique el paquete, si es distinto).", 5),
            ("Destápalo y separa los granos con un tenedor. Mézclalo con las verduras y sirve.", None),
        ],
        "tips": [
            "La proporción habitual es el mismo volumen de líquido que de cuscús, pero revisa el paquete: algunas marcas indican otra.",
        ],
        "image_query": "couscous vegetables",
        "need": ["cuscús", "calabacín", "pimiento", "cebolla"],
    },
    {
        "slug": "aglio-olio",
        "title": "Espaguetis aglio, olio e peperoncino",
        "category": "Pasta",
        "summary": "Pasta con ajo, aceite de oliva y guindilla: pocos ingredientes y una técnica sencilla para que el aceite y el agua de cocción formen una salsa.",
        "servings": 2,
        "total": 20,
        "time_breakdown": ['Calentar el agua: 8–10 min (mientras cortas el ajo y el perejil)', 'Cocer la pasta: 8–10 min (el ajo se dora a la vez)', 'Saltear y servir: 2 min'],
        "difficulty": "Fácil",
        "ingredients": [
            "[200] g de espaguetis",
            "[3-4] {diente|dientes} de ajo",
            "[1] {guindilla|guindillas} (cayena) {seca|secas}, o una pizca de copos de guindilla",
            "[60] ml de aceite de oliva virgen extra",
            "Un puñado de perejil fresco",
            "Sal gruesa para el agua de cocción",
        ],
        "tools": [
            "Olla grande",
            "Sartén amplia",
            "Cuchillo y tabla de cortar",
            "Pinzas de cocina",
            "Cucharón",
            "Colador",
        ],
        "steps": [
            ("Pon a hervir agua abundante con sal en la olla grande.", None),
            ("Pela el ajo y córtalo en láminas finas. Pica el perejil y desmenuza la guindilla.", None),
            ("Cuece los espaguetis 1 minuto menos de lo que indique el paquete: terminarán de hacerse en la sartén.", 9),
            ("Mientras tanto, pon el aceite en la sartén a fuego bajo con el ajo y la guindilla. Cocina 2–3 minutos, hasta que el ajo esté dorado claro. Si se oscurece, amarga.", 3),
            ("Reserva un cucharón de agua de cocción, escurre la pasta y pásala a la sartén junto con esa agua.", None),
            ("Saltea 1–2 minutos a fuego medio, moviendo la pasta con las pinzas, hasta que el aceite y el agua se liguen en una salsa ligera. Añade el perejil y sirve.", 2),
        ],
        "tips": [
            "Tradicionalmente no se sirve con queso rallado, aunque es habitual añadirlo en casa.",
        ],
        "image_query": "spaghetti aglio olio",
        "need": ["pasta", "ajo"],
    },
    {
        "slug": "salteado-de-pollo",
        "title": "Salteado de pollo con verduras",
        "category": "Carne",
        "summary": "Tiras de pechuga de pollo y verduras en juliana, salteadas a fuego fuerte en wok y terminadas con salsa de soja.",
        "servings": 2,
        "total": 20,
        "time_breakdown": ['Cortar: 10 min', 'Saltear: 10 min'],
        "difficulty": "Fácil",
        "ingredients": [
            "[300] g de pechuga de pollo",
            "[1] {pimiento rojo|pimientos rojos}",
            "[1] {calabacín|calabacines}",
            "[1] {zanahoria|zanahorias}",
            "[0.5] {cebolla|cebollas}",
            "[2] {diente|dientes} de ajo",
            "[1] {trozo|trozos} de jengibre fresco de 2 cm (opcional)",
            "[3] {cucharada|cucharadas} de salsa de soja",
            "[1] {cucharada|cucharadas} de aceite de girasol",
            "Sal",
        ],
        "tools": [
            "Wok o sartén grande",
            "Cuchillo y tabla de cortar",
            "Pelador",
            "Espátula",
            "Plato para reservar",
        ],
        "steps": [
            ("Corta la pechuga en tiras finas. Pela la zanahoria y córtala, junto con el pimiento, el calabacín y la cebolla, en tiras finas (juliana). Pica el ajo y ralla el jengibre.", None),
            ("Calienta el aceite en el wok a fuego alto. Añade el pollo con una pizca de sal y saltéalo 4–5 minutos, moviéndolo, hasta que esté dorado por fuera y blanco por dentro, sin partes rosadas. Resérvalo en un plato.", 5),
            ("En el mismo wok, saltea primero la zanahoria y la cebolla 2 minutos, porque tardan más en ablandarse.", 2),
            ("Añade el pimiento y el calabacín y saltea 2–3 minutos más. Las verduras deben quedar tiernas pero todavía crujientes.", 3),
            ("Añade el ajo y el jengibre y remueve 30 segundos, sin que se quemen.", None),
            ("Devuelve el pollo al wok, añade la salsa de soja y saltea 1 minuto más para que todo se impregne. Sirve enseguida.", None),
        ],
        "tips": [
            "Si quieres acompañarlo con arroz o fideos, ten en cuenta que su cocción no está incluida en los 20 minutos, salvo que ya los tengas hechos.",
            "La salsa de soja ya es salada: prueba antes de añadir más sal.",
        ],
        "image_query": "chicken vegetable stir fry",
        "need": ["pollo", "pimiento", "calabacín", "zanahoria", "cebolla", "salsa de soja"],
    },    {
        "slug": "tortitas",
        "title": "Tortitas esponjosas",
        "category": "Desayuno",
        "summary": "Tortitas de sartén tipo americano: una masa de harina, huevo y leche que se hace en un bol y se cocina por tandas en pocos minutos.",
        "servings": 2,
        "total": 20,
        "time_breakdown": ["Preparar la masa: 5 min", "Cocinar por tandas: 12–15 min (depende de cuántas quepan en tu sartén)"],
        "difficulty": "Fácil",
        "ingredients": [
            "[125] g de harina de trigo",
            "[1] {huevo|huevos}",
            "[200] ml de leche",
            "[1] {cucharada|cucharadas} de azúcar",
            "[1] {cucharadita|cucharaditas} de levadura química (polvo de hornear)",
            "[15] g de mantequilla, y un poco más para la sartén",
            "Una pizca de sal",
            "Para servir: miel, sirope o fruta (opcional)",
        ],
        "tools": [
            "Bol grande",
            "Varillas",
            "Sartén antiadherente",
            "Espátula",
            "Cucharón",
            "Microondas o cazo pequeño (para derretir la mantequilla)",
        ],
        "steps": [
            ("Derrite la mantequilla en el microondas (20–30 segundos) o en un cazo pequeño a fuego bajo, y deja que se temple.", None),
            ("En el bol, mezcla la harina, el azúcar, la levadura y la sal.", None),
            ("Añade el huevo, la leche y la mantequilla derretida, y bate con las varillas hasta que no queden grumos grandes. No hace falta que la masa quede perfectamente lisa.", None),
            ("Calienta la sartén a fuego medio y úntala con muy poca mantequilla.", None),
            ("Vierte medio cucharón de masa por tortita. Cuando se formen burbujas en la superficie y los bordes estén firmes (unos 2 minutos), dale la vuelta y cocínala 1 minuto más.", 2),
            ("Repite con el resto de la masa y sirve las tortitas con miel, sirope o fruta.", None),
        ],
        "tips": [
            "La primera tortita suele servir de prueba: si sale pálida, sube un poco el fuego; si se quema por fuera y queda cruda por dentro, bájalo.",
        ],
        "image_query": "pancakes",
        "need": ["harina", "huevos", "leche", "mantequilla", "levadura química"],
    },
    {
        "slug": "pan-con-tomate",
        "title": "Pan con tomate",
        "category": "Desayuno",
        "summary": "Pan tostado con tomate maduro rallado, aceite de oliva y sal. Un desayuno de la cocina catalana y del Mediterráneo que depende de un buen pan y un buen tomate.",
        "servings": 2,
        "total": 10,
        "time_breakdown": ["Tostar el pan: 3 min", "Rallar el tomate y montar: 5 min"],
        "difficulty": "Fácil",
        "ingredients": [
            "[4] {rebanada|rebanadas} de pan de hogaza o de barra",
            "[2] {tomate maduro|tomates maduros}",
            "Aceite de oliva virgen extra",
            "Sal",
            "[1] {diente|dientes} de ajo (opcional)",
        ],
        "tools": [
            "Tostadora, sartén o parrilla",
            "Rallador",
            "Bol",
            "Cuchillo y tabla de cortar",
            "Cuchara",
        ],
        "steps": [
            ("Tuesta el pan hasta que esté dorado y crujiente por fuera, unos 2–4 minutos según la tostadora.", 3),
            ("Si usas ajo, pélalo y frota ligeramente la superficie del pan tostado con él.", None),
            ("Corta los tomates por la mitad y rállalos sobre el bol por el lado del corte. La piel se queda en la mano: deséchala.", None),
            ("Reparte el tomate rallado sobre el pan con la cuchara.", None),
            ("Aliña con un chorro de aceite de oliva y sal al gusto, y sirve enseguida.", None),
        ],
        "tips": [
            "En Cataluña es habitual frotar el tomate partido directamente sobre el pan, en lugar de rallarlo.",
        ],
        "image_query": "pan con tomate",
        "need": ["pan", "tomate"],
    },
    {
        "slug": "huevos-revueltos",
        "title": "Huevos revueltos cremosos",
        "category": "Desayuno",
        "summary": "Huevos batidos y cuajados despacio en mantequilla, removiendo, para que queden cremosos. Se acompañan de pan tostado.",
        "servings": 2,
        "total": 10,
        "time_breakdown": ["Batir los huevos: 2 min", "Cocinar: 3–4 min (el pan se tuesta a la vez)"],
        "difficulty": "Fácil",
        "ingredients": [
            "[4] {huevo|huevos}",
            "[15] g de mantequilla",
            "[2] {cucharada|cucharadas} de leche (opcional)",
            "Sal",
            "Pimienta negra",
            "[2] {rebanada|rebanadas} de pan tostado, para acompañar",
        ],
        "tools": [
            "Sartén antiadherente",
            "Espátula de silicona o cuchara de madera",
            "Bol",
            "Tenedor",
            "Tostadora (para el pan)",
        ],
        "steps": [
            ("Casca los huevos en el bol, añade la leche si la usas y una pizca de sal, y bátelos con el tenedor hasta que la yema y la clara se mezclen.", None),
            ("Pon el pan a tostar. Mientras, derrite la mantequilla en la sartén a fuego medio-bajo.", None),
            ("Vierte los huevos y espera unos segundos a que empiecen a cuajar por el borde.", None),
            ("Remueve despacio con la espátula, llevando el huevo cuajado desde los bordes hacia el centro, durante 2–3 minutos, hasta que estén cuajados pero todavía cremosos.", 3),
            ("Retíralos del fuego un poco antes de que parezcan hechos: el calor de la sartén los termina de cuajar. Sirve con pimienta negra y el pan tostado.", None),
        ],
        "tips": [
            "A fuego fuerte los huevos cuajan en grumos secos; a fuego medio-bajo quedan más cremosos.",
        ],
        "image_query": "scrambled eggs toast",
        "need": ["huevos", "mantequilla"],
    },
    {
        "slug": "mug-cake",
        "title": "Bizcocho de chocolate en taza",
        "category": "Postre",
        "summary": "Un bizcocho individual (mug cake) que se mezcla en la propia taza y se cocina en el microondas en un par de minutos.",
        "servings": 1,
        "total": 5,
        "time_breakdown": ["Mezclar en la taza: 3 min", "Microondas: 1 min 30 s – 2 min 30 s, según la potencia"],
        "difficulty": "Fácil",
        "ingredients": [
            "[4] {cucharada|cucharadas} de harina de trigo",
            "[4] {cucharada|cucharadas} de azúcar",
            "[2] {cucharada|cucharadas} de cacao en polvo sin azúcar",
            "[1] {huevo|huevos}",
            "[3] {cucharada|cucharadas} de leche",
            "[3] {cucharada|cucharadas} de aceite de girasol",
            "Una pizca de sal",
        ],
        "tools": [
            "Taza grande apta para microondas (una por persona, de unos 350 ml)",
            "Microondas",
            "Tenedor",
            "Cuchara sopera (para medir)",
        ],
        "steps": [
            ("En la taza, mezcla con el tenedor la harina, el azúcar, el cacao y la sal.", None),
            ("Añade el huevo y bate bien, rascando el fondo y los lados de la taza para que no queden restos secos.", None),
            ("Añade la leche y el aceite y mezcla hasta que la masa sea homogénea.", None),
            ("Cocina en el microondas a máxima potencia durante 1 minuto y 30 segundos.", None),
            ("Comprueba la superficie: si todavía está húmeda, cocina tandas de 15 segundos más hasta que esté firme. Sube mucho y puede hundirse un poco al enfriar; es normal.", None),
            ("Deja reposar 1 minuto antes de comer: la taza y el bizcocho salen muy calientes.", None),
        ],
        "tips": [
            "Si haces varias raciones, prepara una taza por persona y cocínalas de una en una.",
            "El tiempo depende de la potencia de tu microondas: si se pasa, queda seco y gomoso.",
        ],
        "image_query": "chocolate mug cake",
        "need": ["harina", "huevos", "leche", "cacao"],
    },
    {
        "slug": "yogur-con-frutos-rojos",
        "title": "Yogur con frutos rojos y granola",
        "category": "Postre",
        "summary": "Capas de yogur, fruta y granola en un vaso. Sin cocción y listo en cinco minutos; sirve igual de postre que de desayuno.",
        "servings": 2,
        "total": 5,
        "time_breakdown": ["Lavar y cortar la fruta: 3 min", "Montar los vasos: 2 min"],
        "difficulty": "Fácil",
        "ingredients": [
            "[250] g de yogur natural o griego",
            "[150] g de frutos rojos (fresas, arándanos o frambuesas), frescos o descongelados",
            "[40] g de granola",
            "[2] {cucharadita|cucharaditas} de miel (opcional)",
        ],
        "tools": [
            "Vasos o cuencos (uno por persona)",
            "Colador",
            "Cuchillo y tabla de cortar",
            "Cuchara",
        ],
        "steps": [
            ("Lava los frutos rojos en el colador y sécalos con cuidado. Si usas fresas, quítales el tallo y córtalas en trozos.", None),
            ("Pon una capa de yogur en el fondo de cada vaso.", None),
            ("Añade una capa de fruta y otra de granola.", None),
            ("Repite las capas y termina con fruta y, si quieres, un hilo de miel.", None),
            ("Sírvelo en el momento: si espera, la granola se ablanda con el yogur.", None),
        ],
        "tips": [
            "Si los frutos rojos son congelados, descongélalos antes en la nevera y escúrrelos.",
        ],
        "image_query": "yogurt parfait berries granola",
        "need": ["yogur", "frutos rojos", "granola"],
    },
    {
        "slug": "ensalada-de-garbanzos",
        "title": "Ensalada de garbanzos",
        "category": "Sin cocción",
        "summary": "Garbanzos cocidos de bote con tomate, pepino y cebolla morada, aliñados con aceite y vinagre. Sin encender el fuego.",
        "servings": 2,
        "total": 15,
        "time_breakdown": ["Escurrir y aclarar los garbanzos: 3 min", "Cortar las verduras: 8 min", "Aliñar: 2 min"],
        "difficulty": "Fácil",
        "ingredients": [
            "[250] g de garbanzos cocidos, escurridos (un bote de 400 g suele traer unos 240–250 g)",
            "[1] {tomate|tomates}",
            "[0.5] {pepino|pepinos}",
            "[0.25] {cebolla morada|cebollas moradas}",
            "[3] {cucharada|cucharadas} de aceite de oliva virgen extra",
            "[1] {cucharada|cucharadas} de vinagre de vino",
            "Sal",
            "Pimienta negra",
            "Perejil fresco (opcional)",
        ],
        "tools": [
            "Colador",
            "Bol grande",
            "Cuchillo y tabla de cortar",
            "Cuchara",
        ],
        "steps": [
            ("Escurre los garbanzos en el colador y acláralos bajo el grifo para quitarles el líquido del bote. Déjalos escurrir.", None),
            ("Lava el tomate y el pepino y córtalos en dados pequeños. Pica la cebolla muy fina.", None),
            ("Pon los garbanzos y las verduras en el bol.", None),
            ("Aliña con el aceite, el vinagre, sal y pimienta, y mezcla bien. Añade perejil picado si lo usas.", None),
            ("Se puede servir enseguida; si esperas unos minutos, los garbanzos toman más sabor del aliño.", None),
        ],
        "tips": [
            "Si la cebolla cruda te resulta fuerte, déjala unos minutos en agua fría y escúrrela antes de añadirla.",
        ],
        "image_query": "chickpea salad",
        "need": ["garbanzos", "tomate", "pepino", "cebolla"],
    },    {
        "slug": "tortilla-francesa-con-queso",
        "title": "Tortilla francesa con queso",
        "category": "Desayuno",
        "summary": "Una cena o desayuno rápido con huevos: tortilla francesa jugosa por dentro, doblada sobre queso que se funde con el calor.",
        "servings": 2,
        "total": 10,
        "time_breakdown": ["Batir los huevos: 2 min", "Cuajar las tortillas, una detrás de otra: 3 min cada una"],
        "difficulty": "Fácil",
        "ingredients": [
            "[4] {huevo|huevos}",
            "[40] g de queso rallado que funda bien (emmental, gouda o mozzarella)",
            "[10] g de mantequilla o un chorrito de aceite de oliva",
            "Sal",
            "Pimienta negra",
        ],
        "tools": ["Sartén antiadherente pequeña", "Bol", "Tenedor", "Espátula", "Plato"],
        "steps": [
            ("Casca 2 huevos por tortilla en el bol, añade una pizca de sal y pimienta y bátelos con el tenedor hasta que la clara y la yema se mezclen.", None),
            ("Calienta la sartén a fuego medio con la mitad de la mantequilla. Vierte los huevos batidos y, durante el primer minuto, lleva con la espátula el huevo que cuaja en los bordes hacia el centro.", 2),
            ("Cuando la tortilla esté casi cuajada pero todavía brillante por encima, reparte la mitad del queso sobre una de sus mitades.", None),
            ("Dobla la tortilla por la mitad, déjala 30 segundos más para que el queso se funda y pásala al plato.", None),
            ("Repite con el resto de huevos y de queso para la segunda tortilla.", None),
        ],
        "tips": ["Si la sartén está demasiado caliente, la tortilla se dora y se seca antes de cuajar por dentro."],
        "image_query": "cheese omelette",
        "need": ["huevos", "queso"],
    },
    {
        "slug": "garbanzos-con-espinacas",
        "title": "Garbanzos salteados con espinacas",
        "category": "Legumbres",
        "summary": "Qué cocinar con un bote de garbanzos: salteados en sartén con espinacas frescas, ajo, pimentón y comino. Listos en un cuarto de hora.",
        "servings": 2,
        "total": 15,
        "time_breakdown": ["Escurrir y cortar: 4 min", "Saltear: 8–9 min"],
        "difficulty": "Fácil",
        "ingredients": [
            "[250] g de garbanzos cocidos, escurridos (un bote de 400 g suele traer unos 240–250 g)",
            "[200] g de espinacas frescas",
            "[2] {diente|dientes} de ajo",
            "[1] {cucharadita|cucharaditas} de pimentón dulce",
            "[0.5] {cucharadita|cucharaditas} de comino molido",
            "[2] {cucharada|cucharadas} de aceite de oliva virgen extra",
            "Sal",
        ],
        "tools": ["Sartén grande", "Colador", "Cuchillo y tabla de cortar", "Cuchara de madera"],
        "steps": [
            ("Escurre los garbanzos en el colador y acláralos bajo el grifo. Lava las espinacas si no vienen lavadas.", None),
            ("Pela los ajos y córtalos en láminas.", None),
            ("Calienta el aceite en la sartén a fuego medio y dora el ajo durante 1 minuto, sin que se queme.", None),
            ("Añade las espinacas con una pizca de sal y remueve 2–3 minutos, hasta que se reduzcan.", 3),
            ("Incorpora los garbanzos, el pimentón y el comino, y saltea 4–5 minutos removiendo para que se calienten y tomen sabor. Prueba y ajusta de sal.", 4),
        ],
        "tips": ["El pimentón se quema muy rápido: añádelo junto con los garbanzos, nunca solo en el aceite caliente."],
        "image_query": "chickpeas spinach",
        "need": ["garbanzos", "espinacas", "ajo"],
    },
    {
        "slug": "sopa-de-fideos",
        "title": "Sopa de fideos rápida",
        "category": "Sopas",
        "summary": "Una sopa caliente con caldo ya hecho y fideos finos. Reconfortante y lista en poco más de diez minutos.",
        "servings": 2,
        "total": 12,
        "time_breakdown": ["Calentar el caldo: 5–6 min", "Cocer los fideos: 3–4 min (según el paquete)"],
        "difficulty": "Fácil",
        "ingredients": [
            "[750] ml de caldo (de verduras para una versión vegetariana)",
            "[60] g de fideos finos",
            "Perejil fresco picado (opcional)",
            "Sal",
        ],
        "tools": ["Cazo u olla mediana", "Cucharón", "Cuchillo y tabla de cortar"],
        "steps": [
            ("Pon el caldo en el cazo a fuego fuerte hasta que hierva.", None),
            ("Añade los fideos y cuécelos el tiempo que indique el paquete (los fideos finos suelen tardar 3–4 minutos), removiendo al principio para que no se peguen.", 4),
            ("Prueba y ajusta de sal: muchos caldos comprados ya llevan sal.", None),
            ("Sirve enseguida con perejil picado por encima: si espera, los fideos siguen absorbiendo caldo.", None),
        ],
        "tips": ["Si añades un huevo batido en el último minuto, removiendo, quedará en hebras y la sopa será más completa."],
        "image_query": "noodle soup broth",
        "need": ["caldo", "fideos"],
    },
    {
        "slug": "tostada-de-aguacate-y-huevo",
        "title": "Tostada de aguacate y huevo",
        "category": "Desayuno",
        "summary": "Un desayuno en diez minutos: pan tostado con aguacate machacado y un huevo frito con la yema líquida por encima.",
        "servings": 2,
        "total": 10,
        "time_breakdown": ["Tostar el pan y machacar el aguacate: 4 min", "Freír los huevos: 3 min"],
        "difficulty": "Fácil",
        "ingredients": [
            "[2] {rebanada|rebanadas} de pan de hogaza",
            "[1] {aguacate maduro|aguacates maduros}",
            "[2] {huevo|huevos}",
            "Unas gotas de zumo de limón",
            "Aceite de oliva virgen extra",
            "Sal y pimienta negra",
            "Copos de guindilla (opcional)",
        ],
        "tools": ["Tostadora o sartén", "Sartén pequeña", "Espátula", "Bol", "Tenedor", "Cuchillo y tabla de cortar"],
        "steps": [
            ("Pon el pan a tostar.", None),
            ("Parte el aguacate por la mitad, quita el hueso y saca la pulpa con una cuchara al bol. Macháchala con el tenedor con una pizca de sal y unas gotas de limón.", None),
            ("Calienta un chorrito de aceite en la sartén a fuego medio y fríe los huevos 2–3 minutos, hasta que la clara esté cuajada y la yema siga líquida.", 3),
            ("Reparte el aguacate sobre las tostadas, coloca un huevo encima de cada una y termina con pimienta y, si quieres, copos de guindilla.", None),
        ],
        "tips": ["El aguacate está en su punto cuando cede un poco al apretarlo con el dedo."],
        "image_query": "avocado toast fried egg",
        "need": ["pan", "aguacate", "huevos"],
    },
    {
        "slug": "ensalada-de-pasta",
        "title": "Ensalada de pasta con atún",
        "category": "Pasta",
        "summary": "Pasta corta con tomates cherry, atún, maíz y aceitunas. Sirve para comer en casa o llevar en táper.",
        "servings": 2,
        "total": 20,
        "time_breakdown": ["Calentar el agua: 8–10 min (mientras cortas el resto)", "Cocer la pasta: 10–11 min", "Enfriar y mezclar: 2 min"],
        "difficulty": "Fácil",
        "ingredients": [
            "[160] g de pasta corta (fusilli, macarrones o lazos)",
            "[150] g de tomates cherry",
            "[2] {lata|latas} de atún (de unos 80 g escurrido cada una)",
            "[100] g de maíz dulce cocido",
            "[40] g de aceitunas negras sin hueso",
            "[3] {cucharada|cucharadas} de aceite de oliva virgen extra",
            "[1] {cucharada|cucharadas} de vinagre de vino",
            "Sal",
        ],
        "tools": ["Olla grande", "Colador", "Bol grande", "Cuchillo y tabla de cortar", "Cuchara"],
        "steps": [
            ("Pon a hervir agua abundante con sal en la olla.", None),
            ("Mientras se calienta, corta los tomates cherry por la mitad y las aceitunas en rodajas. Escurre el atún y el maíz.", None),
            ("Cuece la pasta el tiempo que indique el paquete.", 10),
            ("Escúrrela y pásala bajo el grifo de agua fría para cortar la cocción y enfriarla. Escúrrela bien.", None),
            ("Mezcla en el bol la pasta con el resto de ingredientes y aliña con el aceite, el vinagre y sal.", None),
        ],
        "tips": ["Se conserva en la nevera, tapada, hasta el día siguiente. Aliña justo antes de comer para que la pasta no absorba todo el aceite."],
        "image_query": "pasta salad tuna",
        "need": ["pasta", "atún", "tomate"],
    },
    {
        "slug": "wrap-de-pollo",
        "title": "Wrap de pollo",
        "category": "Carne",
        "summary": "Tortilla de trigo enrollada con tiras de pollo a la plancha, lechuga, tomate y una salsa de yogur. Para cenar o para llevar.",
        "servings": 2,
        "total": 20,
        "time_breakdown": ["Cortar: 5 min", "Cocinar el pollo: 6–7 min", "Montar los wraps: 5 min"],
        "difficulty": "Fácil",
        "ingredients": [
            "[2] {tortilla|tortillas} de trigo {grande|grandes}",
            "[250] g de pechuga de pollo",
            "[1] {tomate|tomates}",
            "[4] {hoja|hojas} de lechuga",
            "[3] {cucharada|cucharadas} de yogur natural (o mayonesa)",
            "[0.5] {cucharadita|cucharaditas} de pimentón dulce",
            "[1] {cucharada|cucharadas} de aceite de oliva",
            "Sal",
        ],
        "tools": ["Sartén", "Cuchillo y tabla de cortar", "Espátula", "Bol pequeño", "Cuchara"],
        "steps": [
            ("Corta la pechuga en tiras finas y sazónalas con sal y el pimentón.", None),
            ("Lava la lechuga y el tomate. Corta la lechuga en tiras y el tomate en rodajas finas.", None),
            ("Calienta el aceite en la sartén a fuego medio-alto y cocina el pollo 6–7 minutos, dándole la vuelta, hasta que esté dorado por fuera y blanco por dentro, sin partes rosadas.", 6),
            ("Calienta las tortillas unos segundos en la sartén para que se vuelvan flexibles.", None),
            ("Unta cada tortilla con yogur, reparte la lechuga, el tomate y el pollo en el centro, dobla los extremos hacia dentro y enróllala.", None),
        ],
        "tips": ["Envuelto en papel de aluminio o de horno, se lleva bien para comer fuera de casa."],
        "image_query": "chicken wrap",
        "need": ["tortillas de trigo", "pollo", "tomate", "lechuga"],
    },
    {
        "slug": "lentejas-con-verduras",
        "title": "Lentejas de bote con verduras",
        "category": "Legumbres",
        "summary": "Un plato de cuchara sin horas de cocción: lentejas ya cocidas con un sofrito rápido de zanahoria, cebolla y pimiento.",
        "servings": 2,
        "total": 20,
        "time_breakdown": ["Picar las verduras: 6 min", "Sofrito: 7–8 min", "Cocer con las lentejas: 5 min"],
        "difficulty": "Fácil",
        "ingredients": [
            "[250] g de lentejas cocidas, escurridas (un bote de 400 g suele traer unos 240–260 g)",
            "[1] {zanahoria|zanahorias}",
            "[0.5] {cebolla|cebollas}",
            "[0.5] {pimiento rojo|pimientos rojos}",
            "[1] {diente|dientes} de ajo",
            "[1] {cucharadita|cucharaditas} de pimentón dulce",
            "[200] ml de caldo de verduras o agua",
            "[2] {cucharada|cucharadas} de aceite de oliva virgen extra",
            "Sal",
        ],
        "tools": ["Cazuela u olla mediana", "Colador", "Pelador", "Cuchillo y tabla de cortar", "Cuchara de madera"],
        "steps": [
            ("Escurre las lentejas en el colador y acláralas bajo el grifo.", None),
            ("Pela la zanahoria y pícala en dados pequeños, junto con la cebolla, el pimiento y el ajo: cuanto más pequeños, antes se hacen.", None),
            ("Calienta el aceite en la cazuela a fuego medio y sofríe las verduras con una pizca de sal 7–8 minutos, hasta que estén tiernas.", 7),
            ("Añade el pimentón, remueve unos segundos y vierte enseguida el caldo para que no se queme.", None),
            ("Incorpora las lentejas y deja que hierva suavemente 5 minutos. Prueba de sal y sirve.", 5),
        ],
        "tips": ["Si te gustan más espesas, aplasta unas cuantas lentejas con la cuchara contra la pared de la cazuela."],
        "image_query": "lentil stew vegetables",
        "need": ["lentejas", "zanahoria", "cebolla", "pimiento"],
    },
    {
        "slug": "hummus",
        "title": "Hummus casero",
        "category": "Sin cocción",
        "summary": "Crema de garbanzos con tahini, limón y ajo, triturada en minutos. Para untar en pan o mojar verduras crudas.",
        "servings": 4,
        "total": 10,
        "time_breakdown": ["Escurrir y preparar: 4 min", "Triturar: 3–4 min"],
        "difficulty": "Fácil",
        "ingredients": [
            "[250] g de garbanzos cocidos, escurridos (un bote de 400 g)",
            "[2] {cucharada|cucharadas} de tahini (pasta de sésamo)",
            "El zumo de [1] {limón|limones}",
            "[1] {diente|dientes} de ajo",
            "[3] {cucharada|cucharadas} de aceite de oliva virgen extra, y un poco más para servir",
            "[0.5] {cucharadita|cucharaditas} de comino molido",
            "[3] {cucharada|cucharadas} de agua fría",
            "Sal",
            "Pimentón para decorar (opcional)",
        ],
        "tools": ["Batidora de vaso, picadora o batidora de mano con vaso alto", "Colador", "Exprimidor", "Cuchara", "Bol para servir"],
        "steps": [
            ("Escurre los garbanzos y acláralos bajo el grifo. Exprime el limón y pela el ajo.", None),
            ("Pon en el vaso de la batidora los garbanzos, el tahini, el zumo de limón, el ajo, el aceite, el comino y una pizca de sal.", None),
            ("Tritura 1–2 minutos. Añade el agua fría poco a poco y sigue triturando hasta que quede una crema lisa.", None),
            ("Prueba y ajusta: más sal, más limón o un poco más de agua si está demasiado espeso.", None),
            ("Sírvelo en el bol con un chorrito de aceite y, si quieres, una pizca de pimentón.", None),
        ],
        "tips": ["Se conserva tapado en la nevera unos 3–4 días.", "El tahini se vende en supermercados grandes y tiendas de alimentación árabe o ecológica."],
        "image_query": "hummus",
        "need": ["garbanzos", "tahini", "limón"],
    },
    {
        "slug": "batido-de-platano-y-avena",
        "title": "Batido de plátano y avena",
        "category": "Desayuno",
        "summary": "Un desayuno para tomar en cinco minutos: plátano maduro, leche y copos de avena triturados juntos.",
        "servings": 2,
        "total": 5,
        "time_breakdown": ["Preparar y triturar: 5 min"],
        "difficulty": "Fácil",
        "ingredients": [
            "[2] {plátano maduro|plátanos maduros}",
            "[400] ml de leche (o bebida vegetal)",
            "[40] g de copos de avena",
            "[1] {cucharadita|cucharaditas} de miel (opcional)",
            "Una pizca de canela (opcional)",
        ],
        "tools": ["Batidora de vaso o batidora de mano con vaso alto", "Cuchillo", "Vasos"],
        "steps": [
            ("Pela los plátanos y córtalos en trozos.", None),
            ("Pon en el vaso de la batidora el plátano, la leche, la avena y, si quieres, la miel y la canela.", None),
            ("Tritura 1 minuto, hasta que no queden trozos de avena.", None),
            ("Sírvelo enseguida: si espera, la avena lo va espesando.", None),
        ],
        "tips": ["Cuanto más maduro esté el plátano (con manchas en la piel), más dulce saldrá el batido."],
        "image_query": "banana smoothie",
        "need": ["plátano", "leche", "avena"],
    },
    {
        "slug": "champinones-al-ajillo",
        "title": "Champiñones al ajillo",
        "category": "Verduras",
        "summary": "Una tapa clásica: champiñones salteados a fuego fuerte con ajo, guindilla y perejil.",
        "servings": 2,
        "total": 15,
        "time_breakdown": ["Limpiar y cortar: 5 min", "Saltear: 8–9 min"],
        "difficulty": "Fácil",
        "ingredients": [
            "[400] g de champiñones",
            "[4] {diente|dientes} de ajo",
            "[1] {guindilla|guindillas} (cayena) {seca|secas} (opcional)",
            "[3] {cucharada|cucharadas} de aceite de oliva virgen extra",
            "[50] ml de vino blanco (opcional)",
            "Perejil fresco picado",
            "Sal",
        ],
        "tools": ["Sartén grande", "Cuchillo y tabla de cortar", "Papel de cocina", "Cuchara de madera"],
        "steps": [
            ("Limpia los champiñones con papel de cocina húmedo (sin dejarlos en remojo) y córtalos en cuartos o en láminas gruesas.", None),
            ("Pela los ajos y córtalos en láminas.", None),
            ("Calienta el aceite en la sartén a fuego medio con el ajo y la guindilla durante 1 minuto.", None),
            ("Sube el fuego, añade los champiñones con una pizca de sal y saltéalos 6–8 minutos, hasta que suelten su agua, esta se evapore y empiecen a dorarse.", 7),
            ("Si usas vino, añádelo y deja que se evapore 1–2 minutos. Espolvorea perejil y sirve.", None),
        ],
        "tips": ["Si los champiñones no caben en una sola capa, hazlos en dos tandas: amontonados se cuecen en su agua en vez de dorarse."],
        "image_query": "garlic mushrooms",
        "need": ["champiñones", "ajo"],
    },
]
