# -*- coding: utf-8 -*-
"""
Datos de las recetas. Fuente única de verdad: tools/build.py genera todas las
páginas HTML a partir de esta lista. Para cambiar una receta, edítala aquí y
vuelve a ejecutar:  python3 tools/build.py

Campos:
  slug        nombre de archivo (receta-<slug>.html) e imagen (assets/img/<slug>.webp)
  total       minutos aproximados de principio a fin
  time_breakdown  en qué se van esos minutos
  ingredients cantidades para "servings" raciones: [200] = cantidad que se
              recalcula al cambiar las raciones, [3-4] = rango,
              {singular|plural} = palabra que concuerda con la cantidad anterior
  steps       lista de (texto, minutos_de_temporizador | None)
"""

RECIPES = [
    {
        "slug": "carbonara",
        "title": "Espaguetis a la carbonara",
        "category": "Pasta",
        "summary": "La receta romana: guanciale, yema de huevo, pecorino y pimienta negra. Sin nata: la crema sale del huevo y del agua de cocción.",
        "servings": 2,
        "total": 20,
        "time_breakdown": ['Calentar el agua: 8–10 min (mientras preparas el guanciale, el queso y el huevo)', 'Cocer la pasta: 9–11 min (el guanciale se dora a la vez)', 'Mezclar y servir: 2 min'],
        "difficulty": "Media",
        "ingredients": [
            "[200] g de espaguetis",
            "[100] g de guanciale (o panceta curada si no lo encuentras)",
            "[2] {yema|yemas} de huevo y [1] {huevo entero|huevos enteros}",
            "[40] g de queso pecorino romano rallado, y un poco más para servir",
            "Pimienta negra recién molida",
            "Sal gruesa para el agua de cocción",
        ],
        "tools": [
            "Olla grande",
            "Sartén amplia",
            "Bol",
            "Rallador",
            "Tenedor o varillas",
            "Pinzas de cocina",
            "Colador",
            "Cuchillo y tabla de cortar",
        ],
        "steps": [
            ("Pon a calentar agua abundante en la olla grande. Cuando hierva, échale un buen puñado de sal gruesa.", None),
            ("Mientras se calienta el agua, corta el guanciale en tiras de medio centímetro de grosor y ralla el pecorino.", None),
            ("En el bol, bate las yemas y el huevo entero con el pecorino rallado y abundante pimienta negra hasta obtener una pasta espesa. Resérvala.", None),
            ("Echa los espaguetis en el agua hirviendo y cuécelos el tiempo que indique el paquete para que queden al dente (en la mayoría de marcas, entre 9 y 11 minutos).", 10),
            ("Mientras la pasta se cuece, pon el guanciale en la sartén sin aceite, a fuego medio. Deja que suelte su grasa y se dore hasta quedar crujiente por fuera, unos 5–7 minutos. Apaga el fuego.", 6),
            ("Antes de escurrir la pasta, reserva un vaso del agua de cocción. Escurre los espaguetis y pásalos a la sartén con el guanciale, con el fuego apagado. Mézclalo todo con las pinzas.", None),
            ("Añade la mezcla de huevo y queso y remueve rápido, incorporando el agua de cocción poco a poco (a cucharadas) hasta que se forme una crema brillante que envuelva la pasta. Hazlo fuera del fuego: si la sartén está demasiado caliente, el huevo cuaja y queda en grumos.", None),
            ("Sirve enseguida con un poco más de pecorino y pimienta molida por encima.", None),
        ],
        "tips": [
            "La receta romana tradicional no lleva nata, ni cebolla, ni ajo.",
            "Si sustituyes el pecorino por parmesano, el sabor será más suave y menos salado.",
        ],
        "image_query": "spaghetti carbonara",
    },
    {
        "slug": "gambas-al-ajillo",
        "title": "Gambas al ajillo",
        "category": "Pescado y marisco",
        "summary": "Un clásico de la cocina española: gambas cocinadas en aceite de oliva con ajo laminado y guindilla. Se sirven hirviendo, con pan para mojar.",
        "servings": 2,
        "total": 15,
        "time_breakdown": ['Preparar ingredientes: 8 min', 'Cocinar: 4–5 min'],
        "difficulty": "Fácil",
        "ingredients": [
            "[300] g de gambas peladas (crudas)",
            "[4] {diente|dientes} de ajo",
            "[1] {guindilla|guindillas} (cayena) {seca|secas}",
            "[80] ml de aceite de oliva virgen extra",
            "Un puñado de perejil fresco",
            "Sal",
            "Pan, para acompañar",
        ],
        "tools": [
            "Cazuela de barro pequeña o sartén pequeña",
            "Cuchillo y tabla de cortar",
            "Papel de cocina",
            "Cuchara de madera o espátula",
        ],
        "steps": [
            ("Si las gambas están congeladas, descongélalas antes (en la nevera, la noche anterior). Sécalas bien con papel de cocina y sálalas ligeramente.", None),
            ("Pela los ajos y córtalos en láminas finas. Pica el perejil. Parte la guindilla en dos o tres trozos.", None),
            ("Pon el aceite en la cazuela a fuego medio-bajo y añade el ajo y la guindilla. Deja que el ajo se cocine despacio hasta que empiece a tomar un color dorado muy claro, 1–2 minutos. No dejes que se tueste de más o amargará.", 2),
            ("Sube el fuego a medio-alto y añade las gambas. Cocínalas 2–3 minutos, dándoles la vuelta a mitad, hasta que cambien de color gris a rosado y estén opacas.", 3),
            ("Apaga el fuego, espolvorea el perejil picado y sirve enseguida en la misma cazuela, con pan para mojar el aceite.", None),
        ],
        "tips": [
            "Con gambas pequeñas, reduce el tiempo de cocción: si se pasan, quedan duras.",
            "La cazuela de barro mantiene el calor y el aceite sigue burbujeando al llegar a la mesa.",
        ],
        "image_query": "gambas al ajillo",
    },
    {
        "slug": "ensalada-caprese",
        "title": "Ensalada caprese",
        "category": "Sin cocción",
        "summary": "Tomate, mozzarella fresca y albahaca: los colores de la bandera italiana en un plato que no necesita fuego. Depende por completo de la calidad del tomate.",
        "servings": 2,
        "total": 10,
        "time_breakdown": ['Cortar y montar: 10 min', 'Sin cocción'],
        "difficulty": "Fácil",
        "ingredients": [
            "[2] {tomate maduro grande|tomates maduros grandes}",
            "[1] {bola|bolas} de mozzarella fresca (unos [125] g en total)",
            "Un puñado de hojas de albahaca fresca",
            "Aceite de oliva virgen extra",
            "Sal en escamas",
            "Pimienta negra",
        ],
        "tools": [
            "Cuchillo afilado o de sierra",
            "Tabla de cortar",
            "Fuente o plato llano",
            "Papel de cocina",
        ],
        "steps": [
            ("Lava los tomates, sécalos y córtalos en rodajas de aproximadamente 1 cm de grosor.", None),
            ("Escurre la mozzarella del suero, sécala suavemente con papel de cocina y córtala en rodajas de grosor parecido al del tomate.", None),
            ("Coloca en la fuente las rodajas de tomate y de mozzarella alternándolas, ligeramente superpuestas.", None),
            ("Lava y seca las hojas de albahaca y repártelas entre las rodajas.", None),
            ("Justo antes de servir, aliña con un buen chorro de aceite de oliva, sal en escamas y pimienta negra.", None),
        ],
        "tips": [
            "La versión clásica se aliña solo con aceite, sal y pimienta; el vinagre balsámico es opcional.",
            "Saca los tomates de la nevera con antelación: a temperatura ambiente tienen más sabor.",
        ],
        "image_query": "caprese salad",
    },
    {
        "slug": "salmon-con-esparragos",
        "title": "Salmón a la plancha con espárragos trigueros",
        "category": "Pescado y marisco",
        "summary": "Lomos de salmón con la piel crujiente y espárragos trigueros salteados en la misma sartén. Se termina con unas gotas de limón.",
        "servings": 2,
        "total": 20,
        "time_breakdown": ['Preparar: 5 min', 'Saltear los espárragos: 5–6 min', 'Cocinar el salmón: 6–7 min'],
        "difficulty": "Fácil",
        "ingredients": [
            "[2] {lomo|lomos} de salmón con piel (unos 150 g cada uno)",
            "[1] {manojo|manojos} de espárragos trigueros (unos [250] g en total)",
            "[1] {limón|limones}",
            "[2] {cucharada|cucharadas} de aceite de oliva",
            "Sal",
            "Pimienta negra",
        ],
        "tools": [
            "Sartén antiadherente grande o plancha",
            "Espátula o pinzas",
            "Cuchillo y tabla de cortar",
            "Papel de cocina",
            "Plato para reservar",
        ],
        "steps": [
            ("Seca bien los lomos de salmón con papel de cocina (así la piel se dora y no se pega) y salpimiéntalos por ambos lados.", None),
            ("Lava los espárragos. Dobla cada uno por la base: se parte solo por donde deja de ser leñoso. Desecha la parte dura.", None),
            ("Calienta la mitad del aceite en la sartén a fuego medio-alto. Saltea los espárragos 5–6 minutos, moviéndolos de vez en cuando, hasta que estén tiernos y algo dorados. Sálalos y resérvalos en un plato.", 5),
            ("En la misma sartén, añade el resto del aceite y coloca el salmón con la piel hacia abajo. Cocínalo unos 4 minutos sin moverlo, hasta que la piel esté crujiente y veas que el color opaco sube por el lateral.", 4),
            ("Dale la vuelta y cocínalo 2–3 minutos más. El tiempo exacto depende del grosor: el centro debe quedar opaco y la carne debe separarse en láminas al presionarla.", 3),
            ("Sirve el salmón con los espárragos y un gajo de limón para exprimir por encima.", None),
        ],
        "tips": [
            "Con lomos muy gruesos (más de 3 cm), añade 1–2 minutos más por el segundo lado.",
        ],
        "image_query": "grilled salmon asparagus",
    },
    {
        "slug": "quesadillas",
        "title": "Quesadillas de queso y champiñones",
        "category": "Verduras",
        "summary": "Tortillas de trigo dobladas y tostadas en sartén, rellenas de queso fundido y champiñones salteados con cebolla.",
        "servings": 2,
        "total": 20,
        "time_breakdown": ['Preparar: 5 min', 'Saltear el relleno: 6 min', 'Tostar las quesadillas: 8 min'],
        "difficulty": "Fácil",
        "ingredients": [
            "[2] {tortilla|tortillas} de trigo {grande|grandes}",
            "[150] g de queso que funda bien (Oaxaca, mozzarella o cheddar), rallado",
            "[150] g de champiñones",
            "[0.5] {cebolla|cebollas}",
            "[1] {cucharada|cucharadas} de aceite de oliva",
            "Sal",
        ],
        "tools": [
            "Sartén grande",
            "Espátula ancha",
            "Cuchillo y tabla de cortar",
            "Rallador (si el queso no viene rallado)",
            "Plato",
        ],
        "steps": [
            ("Limpia los champiñones con papel de cocina húmedo y córtalos en láminas. Pica la cebolla fina.", None),
            ("Calienta el aceite en la sartén a fuego medio y saltea la cebolla y los champiñones con una pizca de sal durante 5–6 minutos, hasta que los champiñones suelten su agua y esta se evapore. Pásalos a un plato.", 6),
            ("Limpia la sartén con papel de cocina y vuelve a ponerla a fuego medio, sin aceite.", None),
            ("Coloca una tortilla en la sartén y, sobre una de sus mitades, reparte la parte de champiñones y de queso que le corresponde (el relleno se divide a partes iguales entre las tortillas). Dobla la tortilla por la mitad y presiónala con la espátula.", None),
            ("Tuéstala unos 2 minutos por cada lado, hasta que esté dorada y el queso se haya fundido. Repite con el resto de tortillas.", 2),
            ("Deja reposar un minuto para que el queso no se salga al cortar y córtalas en triángulos.", None),
        ],
        "tips": [
            "Si tu sartén es grande, puedes tostar dos quesadillas a la vez y ahorrar unos minutos.",
        ],
        "image_query": "quesadilla cheese mushroom",
    },
    {
        "slug": "cuscus-con-verduras",
        "title": "Cuscús con verduras salteadas",
        "category": "Verduras",
        "summary": "La sémola de cuscús precocida solo necesita líquido caliente y unos minutos de reposo; mientras tanto, se saltean las verduras.",
        "servings": 2,
        "total": 20,
        "time_breakdown": ['Cortar las verduras: 7 min', 'Saltear: 10 min (el cuscús reposa a la vez)'],
        "difficulty": "Fácil",
        "ingredients": [
            "[150] g de cuscús (sémola precocida)",
            "[150] ml de agua o caldo de verduras",
            "[1] {calabacín|calabacines}",
            "[1] {pimiento rojo|pimientos rojos}",
            "[0.5] {cebolla|cebollas}",
            "[2] {cucharada|cucharadas} de aceite de oliva",
            "[1] {cucharadita|cucharaditas} de comino molido",
            "Sal",
            "Pimienta negra",
        ],
        "tools": [
            "Cazo",
            "Sartén",
            "Bol resistente al calor con tapa (o un plato para taparlo)",
            "Tenedor",
            "Cuchillo y tabla de cortar",
        ],
        "steps": [
            ("Lava el calabacín y el pimiento. Córtalos en dados pequeños, junto con la cebolla, para que se hagan rápido.", None),
            ("Calienta la mitad del aceite en la sartén a fuego medio y sofríe la cebolla 3 minutos.", 3),
            ("Añade el pimiento y el calabacín, sala y cocina 6–7 minutos removiendo de vez en cuando, hasta que estén tiernos. Añade el comino y la pimienta en el último minuto.", 6),
            ("Mientras se hacen las verduras, calienta el agua o el caldo en el cazo con una pizca de sal y el resto del aceite hasta que hierva.", None),
            ("Pon el cuscús en el bol, vierte el líquido hirviendo por encima, tápalo y déjalo reposar 5 minutos (o lo que indique el paquete, si es distinto).", 5),
            ("Destápalo y separa los granos con un tenedor. Mézclalo con las verduras y sirve.", None),
        ],
        "tips": [
            "La proporción habitual es el mismo volumen de líquido que de cuscús, pero revisa el paquete: algunas marcas indican otra.",
        ],
        "image_query": "couscous vegetables",
    },
    {
        "slug": "aglio-olio",
        "title": "Espaguetis aglio, olio e peperoncino",
        "category": "Pasta",
        "summary": "Pasta con ajo, aceite de oliva y guindilla: pocos ingredientes y una técnica sencilla para que el aceite y el agua de cocción formen una salsa.",
        "servings": 2,
        "total": 20,
        "time_breakdown": ['Calentar el agua: 8–10 min (mientras cortas el ajo y el perejil)', 'Cocer la pasta: 8–10 min (el ajo se dora a la vez)', 'Saltear y servir: 2 min'],
        "difficulty": "Fácil",
        "ingredients": [
            "[200] g de espaguetis",
            "[3-4] {diente|dientes} de ajo",
            "[1] {guindilla|guindillas} (cayena) {seca|secas}, o una pizca de copos de guindilla",
            "[60] ml de aceite de oliva virgen extra",
            "Un puñado de perejil fresco",
            "Sal gruesa para el agua de cocción",
        ],
        "tools": [
            "Olla grande",
            "Sartén amplia",
            "Cuchillo y tabla de cortar",
            "Pinzas de cocina",
            "Cucharón",
            "Colador",
        ],
        "steps": [
            ("Pon a hervir agua abundante con sal en la olla grande.", None),
            ("Pela el ajo y córtalo en láminas finas. Pica el perejil y desmenuza la guindilla.", None),
            ("Cuece los espaguetis 1 minuto menos de lo que indique el paquete: terminarán de hacerse en la sartén.", 9),
            ("Mientras tanto, pon el aceite en la sartén a fuego bajo con el ajo y la guindilla. Cocina 2–3 minutos, hasta que el ajo esté dorado claro. Si se oscurece, amarga.", 3),
            ("Reserva un cucharón de agua de cocción, escurre la pasta y pásala a la sartén junto con esa agua.", None),
            ("Saltea 1–2 minutos a fuego medio, moviendo la pasta con las pinzas, hasta que el aceite y el agua se liguen en una salsa ligera. Añade el perejil y sirve.", 2),
        ],
        "tips": [
            "Tradicionalmente no se sirve con queso rallado, aunque es habitual añadirlo en casa.",
        ],
        "image_query": "spaghetti aglio olio",
    },
    {
        "slug": "salteado-de-pollo",
        "title": "Salteado de pollo con verduras",
        "category": "Carne",
        "summary": "Tiras de pechuga de pollo y verduras en juliana, salteadas a fuego fuerte en wok y terminadas con salsa de soja.",
        "servings": 2,
        "total": 20,
        "time_breakdown": ['Cortar: 10 min', 'Saltear: 10 min'],
        "difficulty": "Fácil",
        "ingredients": [
            "[300] g de pechuga de pollo",
            "[1] {pimiento rojo|pimientos rojos}",
            "[1] {calabacín|calabacines}",
            "[1] {zanahoria|zanahorias}",
            "[0.5] {cebolla|cebollas}",
            "[2] {diente|dientes} de ajo",
            "[1] {trozo|trozos} de jengibre fresco de 2 cm (opcional)",
            "[3] {cucharada|cucharadas} de salsa de soja",
            "[1] {cucharada|cucharadas} de aceite de girasol",
            "Sal",
        ],
        "tools": [
            "Wok o sartén grande",
            "Cuchillo y tabla de cortar",
            "Pelador",
            "Espátula",
            "Plato para reservar",
        ],
        "steps": [
            ("Corta la pechuga en tiras finas. Pela la zanahoria y córtala, junto con el pimiento, el calabacín y la cebolla, en tiras finas (juliana). Pica el ajo y ralla el jengibre.", None),
            ("Calienta el aceite en el wok a fuego alto. Añade el pollo con una pizca de sal y saltéalo 4–5 minutos, moviéndolo, hasta que esté dorado por fuera y blanco por dentro, sin partes rosadas. Resérvalo en un plato.", 5),
            ("En el mismo wok, saltea primero la zanahoria y la cebolla 2 minutos, porque tardan más en ablandarse.", 2),
            ("Añade el pimiento y el calabacín y saltea 2–3 minutos más. Las verduras deben quedar tiernas pero todavía crujientes.", 3),
            ("Añade el ajo y el jengibre y remueve 30 segundos, sin que se quemen.", None),
            ("Devuelve el pollo al wok, añade la salsa de soja y saltea 1 minuto más para que todo se impregne. Sirve enseguida.", None),
        ],
        "tips": [
            "Si quieres acompañarlo con arroz o fideos, ten en cuenta que su cocción no está incluida en los 20 minutos, salvo que ya los tengas hechos.",
            "La salsa de soja ya es salada: prueba antes de añadir más sal.",
        ],
        "image_query": "chicken vegetable stir fry",
    },
]
